set(AEVOX_VERSION_BASE "${PROJECT_VERSION}")
set(AEVOX_VERSION_PRERELEASE "alpha.0" CACHE STRING "Aevox prerelease suffix")

if(AEVOX_VERSION_PRERELEASE STREQUAL "")
    set(AEVOX_VERSION_FULL "${AEVOX_VERSION_BASE}")
else()
    set(AEVOX_VERSION_FULL "${AEVOX_VERSION_BASE}-${AEVOX_VERSION_PRERELEASE}")
endif()

message(STATUS "Aevox version: ${AEVOX_VERSION_FULL}")
